# Generated by Django 4.2 on 2024-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="actions",
        ),
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="بازدید"),
        ),
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                related_name="comments_post",
                to="contents.comment",
                verbose_name="نظرات",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="keyword_posts",
                to="contents.keyword",
                verbose_name="کلمات کلیدی",
            ),
        ),
        migrations.DeleteModel(
            name="Interaction",
        ),
    ]
