# Generated by Django 4.2 on 2024-07-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='techonologies',
            new_name='technologies',
        ),
    ]
