# Generated by Django 4.2 on 2024-07-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_rename_techonologies_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شناسه'),
        ),
    ]
