# Generated by Django 4.2 on 2024-08-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_project_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='technology',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام انگلیسی'),
        ),
    ]
