# Generated by Django 4.2 on 2024-08-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_category_english_name_keyword_english_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='posts', to='contents.keyword', verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='contents.technology', verbose_name='تکنولوژی\u200cها'),
        ),
    ]
