# Generated by Django 4.2 on 2024-08-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_post_keywords_alter_project_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_img',
            new_name='header_image',
        ),
    ]
