# Generated by Django 4.2 on 2024-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0008_rename_header_img_post_header_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="english_name",
        ),
        migrations.RemoveField(
            model_name="keyword",
            name="english_name",
        ),
        migrations.RemoveField(
            model_name="technology",
            name="english_name",
        ),
        migrations.AlterField(
            model_name="post",
            name="header",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="چکیده"
            ),
        ),
    ]
