# Generated by Django 4.2 on 2024-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0009_remove_category_english_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="قابل مشاهده"),
        ),
    ]
