# Generated by Django 4.2 on 2024-10-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0010_project_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="وضعیت"
            ),
        ),
    ]
