# Generated by Django 4.2 on 2024-11-06 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contents", "0011_image_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="english_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نام انگلیسی"
            ),
        ),
        migrations.AddField(
            model_name="keyword",
            name="english_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نام انگلیسی"
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="english_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نام انگلیسی"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
