# Generated by Django 4.2 on 2025-02-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0013_post_english_header_post_english_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
                ("priority", models.IntegerField(verbose_name="اولویت")),
                (
                    "selcected_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contents.post",
                        verbose_name="پست انتخاب شده",
                    ),
                ),
            ],
            options={
                "verbose_name": "محتوای منتخب",
                "verbose_name_plural": "محتوای منتخب",
            },
        ),
    ]
