# Generated by Django 4.2 on 2025-02-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0014_choicecontent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choicecontent",
            old_name="selcected_post",
            new_name="selceted_post",
        ),
    ]
