# Generated by Django 4.2 on 2025-02-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0015_rename_selcected_post_choicecontent_selceted_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choicecontent",
            old_name="selceted_post",
            new_name="selected_post",
        ),
    ]
