# Generated by Django 4.2 on 2025-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_rename_selceted_post_choicecontent_selected_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicecontent',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='اولویت'),
        ),
    ]
