# Generated by Django 4.2 on 2025-04-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_alter_choicecontent_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروز\u200cرسانی')),
                ('channel_id', models.CharField(max_length=200, verbose_name='آیدی کانال')),
                ('is_selected', models.BooleanField(default=False, verbose_name='انتخاب شده')),
                ('type_channel', models.CharField(choices=[('post', 'پست'), ('project', 'پروژه')], max_length=100, verbose_name='نوع کانال')),
            ],
            options={
                'verbose_name': 'تلگرام',
                'verbose_name_plural': 'تلگرام ها',
            },
        ),
    ]
