# Generated by Django 4.2 on 2024-07-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام خانوادگی')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/photo/', verbose_name='تصویر پروفایل')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروز\u200cرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'حساب اجتماعی',
                'verbose_name_plural': 'حساب\u200cهای اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='UserAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروز\u200cرسانی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('skill', models.CharField(max_length=200, verbose_name='مهارت')),
                ('university_name', models.CharField(max_length=300, verbose_name='نام دانشگاه')),
                ('university_web', models.URLField(blank=True, null=True, verbose_name='آدرس دانشگاه')),
                ('socials', models.ManyToManyField(related_name='user_socials', to='accounts.social', verbose_name='حساب\u200cهای اجتماعی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درباره کاربران',
                'verbose_name_plural': 'درباره کاربران',
            },
        ),
    ]
