# Generated by Django 4.2 on 2024-07-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/photo/",
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
