# Generated by Django 4.2 on 2024-07-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروز\u200cرسانی')),
                ('types', models.CharField(max_length=20, verbose_name='نوع پروژه')),
                ('name', models.CharField(max_length=300, verbose_name='نام کامل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('website_url', models.URLField(verbose_name='آدرس سایت مشابه')),
                ('website_image', models.ImageField(upload_to='cooperation/site_images/', verbose_name='نمونه تصویر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'هماکاری',
                'verbose_name_plural': 'همکاری ها',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='users/photo/userimg.png', upload_to='users/photo/', verbose_name='تصویر پروفایل'),
        ),
    ]
