# Generated by Django 4.2 on 2024-10-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_cooperation_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="وضعیت"
            ),
        ),
        migrations.AlterField(
            model_name="userabout",
            name="socials",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_socials",
                to="accounts.social",
                verbose_name="حساب\u200cهای اجتماعی",
            ),
        ),
    ]
