# Generated by Django 4.2 on 2024-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_opt",
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="qrcode_image",
            field=models.ImageField(blank=True, null=True, upload_to="users/qimages/"),
        ),
    ]
