# Generated by Django 4.2 on 2024-11-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_is_otp_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userabout",
            name="english_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="توضیحات انگلیسی"
            ),
        ),
        migrations.AddField(
            model_name="userabout",
            name="english_skill",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="مهارت انگلیسی"
            ),
        ),
        migrations.AddField(
            model_name="userabout",
            name="english_university_name",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="نام دانشگاه انگلیسی",
            ),
        ),
        migrations.AlterField(
            model_name="userabout",
            name="skill",
            field=models.CharField(max_length=500, verbose_name="مهارت"),
        ),
    ]
