# Generated by Django 4.2 on 2024-11-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_userabout_english_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="وضعیت"
                    ),
                ),
            ],
            options={
                "verbose_name": "مهارت",
                "verbose_name_plural": "مهارت ها",
            },
        ),
        migrations.RemoveField(
            model_name="userabout",
            name="english_skill",
        ),
        migrations.RemoveField(
            model_name="userabout",
            name="skill",
        ),
        migrations.AddField(
            model_name="userabout",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="skill_about",
                to="accounts.skill",
                verbose_name="مهارت\u200cها",
            ),
        ),
    ]
